# Generated by Django 5.2.12 on 2026-03-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='攝影機顯示名稱', max_length=100, unique=True)),
                ('rtsp_url', models.CharField(help_text='RTSP 連線字串', max_length=500)),
                ('is_enabled', models.BooleanField(default=True, help_text='是否啟用此攝影機')),
                ('description', models.TextField(blank=True, help_text='備註或說明（選填）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Camera Source',
                'verbose_name_plural': 'Camera Sources',
            },
        ),
    ]
