# Generated by Django 5.2.12 on 2026-03-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camerasource',
            name='description',
        ),
        migrations.RemoveField(
            model_name='camerasource',
            name='rtsp_url',
        ),
        migrations.AddField(
            model_name='camerasource',
            name='cctv_pass',
            field=models.CharField(default='temp_pass', help_text='CCTV 登入密碼', max_length=100),
        ),
        migrations.AddField(
            model_name='camerasource',
            name='cctv_user',
            field=models.CharField(default='temp_user', help_text='CCTV 登入帳號', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camerasource',
            name='device_id',
            field=models.CharField(default='0001', help_text='設備編號', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camerasource',
            name='rtsp_port',
            field=models.IntegerField(default=554, help_text='RTSP 埠號'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camerasource',
            name='stream_url',
            field=models.CharField(default='rtsp://IP:Port/chID=1&streamType=main', help_text='串流 URL（例如 RTSP）', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camerasource',
            name='web_port',
            field=models.IntegerField(default=80, help_text='Web 存取埠號'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camerasource',
            name='name',
            field=models.CharField(help_text='攝影機顯示名稱', max_length=100),
        ),
    ]
