# Generated by Django 5.2.12 on 2026-03-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_remove_camerasource_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerasource',
            name='is_online',
            field=models.BooleanField(default=False, help_text='最近一次連線檢查是否在線'),
        ),
        migrations.AddField(
            model_name='camerasource',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, help_text='最近一次連線檢查時間', null=True),
        ),
    ]
