# Generated by Django 5.2.12 on 2026-03-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_camerasource_is_online_camerasource_last_checked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerasource',
            name='name',
            field=models.CharField(db_index=True, help_text='攝影機顯示名稱', max_length=100),
        ),
    ]
