# Generated by Django 5.2.12 on 2026-03-23 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_alter_camerasource_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(help_text='變化後的連線狀態')),
                ('changed_at', models.DateTimeField(help_text='狀態變化時間')),
                ('camera', models.ForeignKey(help_text='所屬攝影機', on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='cameras.camerasource')),
            ],
            options={
                'verbose_name': 'Camera Status Log',
                'verbose_name_plural': 'Camera Status Logs',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['camera', '-changed_at'], name='cameras_cam_camera__2d3b66_idx')],
            },
        ),
    ]
