# Generated by Django 5.2.12 on 2026-03-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0005_camerastatuslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerasource',
            name='cctv_pass',
            field=models.CharField(blank=True, default='', help_text='CCTV 登入密碼', max_length=100),
        ),
        migrations.AlterField(
            model_name='camerasource',
            name='cctv_user',
            field=models.CharField(blank=True, default='', help_text='CCTV 登入帳號', max_length=100),
        ),
    ]
